services:
  bot:
    image: ghcr.io/dragonpaw/discord-bot:latest
    restart: unless-stopped
    environment:
      - BOT_TOKEN
      - CLIENT_ID
    volumes:
      - bot-state:/app/state

volumes:
  bot-state:
